### PR TITLE
Merge recent commits from `sailfishos-applications/filecase:devel`

### PR DESCRIPTION
**Pull request by Olf0**
Please merge this PR (i.e. by performing a regular "merge commit", *not* a "squash commit"), then create a PR of `Logic-gate/filecase:devel` to `sailfishos-applications/filecase:rectify-webdav`.
Thanks!

<sub>P.S.: Please note that the usual convention is to open a new "topic branch" when suggesting changes, then pose a PR from this topic branch to the default branch at origin; GitHub suggests `<username>-patch-N` (with N = 1, 2, 3, …; depending on how many PRs one poses in parallel) when doing this via the GitHub web-frontend: This way the default branch (here: `devel`) in your git repo keeps reflecting the default branch in the origin(al) repo at the time of cloning it.  When there were additional commits to the default branch at origin (happened here) this is much easier to resolve if your changes are in a separate feature branch.</sub>

<sub>But there is nothing which cannot be addressed by another ("level of" in the original phrase) indirection: Hence I created the `rectify-webdav` feature branch at origin to proceed.  Please pose a PR with your changes (i.e. from `Logic-gate/filecase:devel`) to it, after having merged this PR.</sub>

### CODE REVIEW

**Review by Olf0 — COMMENTED** [review]
LGTM

P.S.: Please let us discuss [the specifics of your changes](https://github.com/sailfishos-applications/filecase/issues/48#issuecomment-1825740114) in the PR you pose to `sailfishos-applications/filecase:rectify-webdav` after merging this one.

**Comment by Logic-gate** [comment]
I cant create a PR, `Pull request creation failed. Validation failed: must be a collaborator`

**Comment by Olf0** [comment]
> I cant create a PR, `Pull request creation failed. Validation failed: must be a collaborator`

Oh, this is not how it ought to be: Everybody should be allowed to pose PRs.  Thank you for trying and notifying me.  I will have a look a little later.

**Comment by Olf0** [comment]
> I cant create a PR, `Pull request creation failed. Validation failed: must be a collaborator`

**Where** do you see this message?  I.e., are you trying to pose the PR in VScode / VSstudio or the GitHub-app?

If so, please try at GitHub's web-frontend; this should be [the correct link to start](https://github.com/sailfishos-applications/filecase/compare/rectify-webdav...Logic-gate:filecase:devel) with.

**Comment by Olf0** [comment]
Arrgh, often I love Git, sometimes I still hate it: Your resulting PR [should look like this](https://github.com/sailfishos-applications/filecase/pull/59).

1. Do you manage to pose a similar PR?
2. But as you see, because commits are diffs at a certain point in time, there is "nothing to commit"; there sure is, it is still in your `devel` branch, but those commits are temporally before the merge commit from `sailfishos-applications:filecase:rectify-webdav`.  One way to handle that would be:
   1. ~~I revert this merge here.~~
   2. ~~You rebase your `devel` on `sailfishos-applications:filcase:devel`.  If you do not want to do that at the git command line, I can instruct you how to achieve this at GitHub's web-frontend, it is just a few clicks:~~
      1. ~~Open a PR: https://github.com/sailfishos-applications/filecase/compare/devel...Logic-gate:filecase:devel~~
      2. ~~Hit the `rebase` button.~~
  
   Better way, how it should have been in the first place:
   1. Branch your `devel` branch to a feature branch, e.g. `fix-webdav`.
   2. Create a PR from that feature branch to `origin:devel`.

**Pull request merged**
